name: UltimateSpawn
version: 0.1.2
author: Dianox
main: fr.Dianox.US.MainClass.MainClass
LOAD: POSTWORLD
commands:
    spawn:
        description: Teleports player to the spawn
        aliases: [hub, lobby, l, h]
    setspawn:
        description: Set the spawn
        aliases: [sethub, setlobby]
    ultimatespawn:
        description: Show help of UltimateSpawn
        aliases: us
    ping:
        description: Show the ping
    cc:
        description: Show help of clearchat
