name: UltimateSpawn
version: 0.6-Alpha
author: Dianox
main: fr.Dianox.US.MainClass.MainClass
LOAD: POSTWORLD
softdepend: [PlaceholderAPI]
commands:
    spawn:
        description: Teleports player to the spawn
        aliases: [hub, lobby, l, h]
    setspawn:
        description: Set the spawn
        aliases: [sethub, setlobby]
    ultimatespawn:
        description: Show help of UltimateSpawn
        aliases: us
    ping:
        description: Show the ping
    cc:
        description: Show help of clearchat
    bc:
        description: Broadcast
        aliases: [broadcast]
    globalmute:
        description: Mute all the chat
        aliases: [gmute]
    delaychat:
        description: Put a delay for the chat
        aliases: [dchat]
    fly:
        description: Enable or disable the fly of a player
